[project]
name = "microspike"
version = "0.1.0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mehran", email = "mehranfaraji377@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "ipywidgets>=8.1.5",
    "matplotlib>=3.9.2",
    "numba>=0.60.0",
    "numpy>=2.0.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
    publish-url = "https://test.pypi.org/legacy/"
